In [1]:
import numpy as np
def myfunction(x,N):
    print( np.array(x))
    print (np.vander(x, N))
    print(np.column_stack([x**(N-1-i) for i in range(N)]))
    print(np.vander(x, increasing=False))

In [3]:
x=np.array([1,2,3,5])
myfunction(x,3)

[1 2 3 5]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
